//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServerApp.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Position", Namespace="http://schemas.datacontract.org/2004/07/Proxy")]
    public partial class Position : object
    {
        
        private double latitudeField;
        
        private double longitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JCDStation", Namespace="http://schemas.datacontract.org/2004/07/Proxy")]
    public partial class JCDStation : object
    {
        
        private RoutingServerApp.Service.MainStands mainStandsField;
        
        private string nameField;
        
        private int numberField;
        
        private RoutingServerApp.Service.Position positionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoutingServerApp.Service.MainStands mainStands
        {
            get
            {
                return this.mainStandsField;
            }
            set
            {
                this.mainStandsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoutingServerApp.Service.Position position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MainStands", Namespace="http://schemas.datacontract.org/2004/07/Proxy")]
    public partial class MainStands : object
    {
        
        private RoutingServerApp.Service.Availabilities availabilitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoutingServerApp.Service.Availabilities availabilities
        {
            get
            {
                return this.availabilitiesField;
            }
            set
            {
                this.availabilitiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Availabilities", Namespace="http://schemas.datacontract.org/2004/07/Proxy")]
    public partial class Availabilities : object
    {
        
        private int bikesField;
        
        private int electricalBikesField;
        
        private int mechanicalBikesField;
        
        private int standsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bikes
        {
            get
            {
                return this.bikesField;
            }
            set
            {
                this.bikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int electricalBikes
        {
            get
            {
                return this.electricalBikesField;
            }
            set
            {
                this.electricalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mechanicalBikes
        {
            get
            {
                return this.mechanicalBikesField;
            }
            set
            {
                this.mechanicalBikesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stands
        {
            get
            {
                return this.standsField;
            }
            set
            {
                this.standsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingServerApp.Service.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetNearestStation", ReplyAction="http://tempuri.org/IService/GetNearestStationResponse")]
        System.Threading.Tasks.Task<RoutingServerApp.Service.JCDStation> GetNearestStationAsync(RoutingServerApp.Service.Position origin, bool isCheckingBikeAvailability);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceChannel : RoutingServerApp.Service.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RoutingServerApp.Service.IService>, RoutingServerApp.Service.IService
    {
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RoutingServerApp.Service.JCDStation> GetNearestStationAsync(RoutingServerApp.Service.Position origin, bool isCheckingBikeAvailability)
        {
            return base.Channel.GetNearestStationAsync(origin, isCheckingBikeAvailability);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
